export const listNotice = [
  {
    no_content_txt: " This is Notice 1",
    no_created: 1691140791,
    no_idx: 71,
    no_subject: "Notice 1",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 2",
    no_created: 1691142791,
    no_idx: 72,
    no_subject: "Notice 2",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 3",
    no_created: 1691140791,
    no_idx: 73,
    no_subject: "Notice 3",
    no_status: "REQUEST",
  },
  {
    no_content_txt: " This is Notice 4",
    no_created: 1691140791,
    no_idx: 74,
    no_subject: "Notice 4",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 5",
    no_created: 1691140791,
    no_idx: 75,
    no_subject: "Notice 5",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 6",
    no_created: 6696640796,
    no_idx: 76,
    no_subject: "Notice 6",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 7",
    no_created: 1691140791,
    no_idx: 77,
    no_subject: "Notice 7",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 8",
    no_created: 1691140791,
    no_idx: 78,
    no_subject: "Notice 8",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 9",
    no_created: 1691140791,
    no_idx: 79,
    no_subject: "Notice 9",
    no_status: "ACTIVE",
  },
  {
    no_content_txt: " This is Notice 10",
    no_created: 1691140791,
    no_idx: 80,
    no_subject: "Notice 10",
    no_status: "ACTIVE",
  },
];
